/********************************************************************************
** Form generated from reading UI file 'ApplicationWindow.ui'
**
** Created by: Qt User Interface Compiler version 6.10.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_APPLICATIONWINDOW_H
#define UI_APPLICATIONWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDockWidget>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMdiArea>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QSplitter>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>
#include "Folder.h"

QT_BEGIN_NAMESPACE

class Ui_ApplicationWindow
{
public:
    QAction *actionOpenAproj;
    QAction *actionOpenImage;
    QAction *actionImportImage;
    QAction *actionSaveProject;
    QAction *actionSaveProjectAs;
    QAction *actionOpenTemplate;
    QAction *actionSaveAsTemplate;
    QAction *actionPrint;
    QAction *actionPrintAllPlots;
    QAction *actionExportASCII;
    QAction *actionImportASCII;
    QAction *actionQuit;
    QAction *actionNewProject;
    QAction *actionNewTable;
    QAction *actionNewMatrix;
    QAction *actionNewNote;
    QAction *actionNewGraph;
    QAction *actionNewFunctionPlot;
    QAction *actionNew3DSurfacePlot;
    QAction *actionExportCurrentGraph;
    QAction *actionExportAllGraphs;
    QAction *actionUndo;
    QAction *actionRedo;
    QAction *actionCutSelection;
    QAction *actionCopySelection;
    QAction *actionClearSelection;
    QAction *actionPasteSelection;
    QAction *actionDeleteFitTables;
    QAction *actionClearLogInfo;
    QAction *actionPreferences;
    QAction *actionShowFileToolbar;
    QAction *actionShowEditToolbar;
    QAction *actionShowGraphToolbar;
    QAction *actionShowPlotToolbar;
    QAction *actionShowTableToolbar;
    QAction *actionShowMatrixPlotToolbar;
    QAction *actionShow3DSurfacePlotToolbar;
    QAction *actionLockToolbars;
    QAction *actionPlotWizard;
    QAction *actionShowUndoRedoHistory;
    QAction *actionAddRemoveCurve;
    QAction *actionAddErrorBars;
    QAction *actionAddFunctionCurve;
    QAction *actionAddText;
    QAction *actionDrawArrow;
    QAction *actionDrawLine;
    QAction *actionAddTimeStamp;
    QAction *actionAddImage;
    QAction *actionDrawEllipse;
    QAction *actionAddNestedLayout;
    QAction *actionRemoveLayout;
    QAction *actionArrangeLayout;
    QAction *actionHelp;
    QAction *actionHomepage;
    QAction *actionChooseHelpFolder;
    QAction *actionCheckUpdates;
    QAction *actionDownloadManual;
    QAction *actionVisitForum;
    QAction *actionReportBug;
    QAction *actionAbout;
    QAction *actionPlot2DLine;
    QAction *actionPlot2DVerticalBars;
    QAction *actionPlot2DHorizontalBars;
    QAction *actionPlot2DArea;
    QAction *actionPlot2DPie;
    QAction *actionPlot2DVectorsXYXY;
    QAction *actionPlot2DVectorsXYAM;
    QAction *actionPlot2DVerticalDropLines;
    QAction *actionPlot2DSpline;
    QAction *actionPlot2DVerticalSteps;
    QAction *actionPlot2DHorizontalSteps;
    QAction *actionPlot2DStatBox;
    QAction *actionPlot2DStatHistogram;
    QAction *actionPlot2DStatStackedHistogram;
    QAction *actionPanelVertical2Layouts;
    QAction *actionPanelHorizontal2Layouts;
    QAction *actionPanel4Layouts;
    QAction *actionPlot3DRibbon;
    QAction *actionPlot3DBar;
    QAction *actionPlot3DScatter;
    QAction *actionPlot3DTrajectory;
    QAction *actionPlot2DLineSymbol;
    QAction *actionScriptingLanguage;
    QAction *actionRestartScripting;
    QAction *actionExecute;
    QAction *actionExecuteAll;
    QAction *actionEvaluateExpression;
    QAction *action3DWireFrame;
    QAction *action3DSurface;
    QAction *action3DWireSurface;
    QAction *action3DBar;
    QAction *action3DScatter;
    QAction *action3DCountourColorFill;
    QAction *action3DCountourLines;
    QAction *action3DGreyScaleMap;
    QAction *actionCascadeWindow;
    QAction *actionTileWindow;
    QAction *actionNextWindow;
    QAction *actionPreviousWindow;
    QAction *actionDuplicateWindow;
    QAction *actionHideWindow;
    QAction *actionCloseWindow;
    QAction *actionStatisticsOnColumns;
    QAction *actionStatisticsOnRows;
    QAction *actionGraph2DFFT;
    QAction *actionCorrelate;
    QAction *actionAutocorrelate;
    QAction *actionConvolute;
    QAction *actionDeconvolute;
    QAction *actionGraph2DFitWizard;
    QAction *actionHorizontalTranslate;
    QAction *actionVerticalTranslate;
    QAction *actionDifferentiate;
    QAction *actionIntegrate;
    QAction *actionInterpolate;
    QAction *actionSavitzkySmooth;
    QAction *actionMovingWindowAverageSmooth;
    QAction *actionFFTFilterSmooth;
    QAction *actionLowPassFFTFilter;
    QAction *actionHighPassFFTFilter;
    QAction *actionBandPassFFTFilter;
    QAction *actionBandBlockFFTFilter;
    QAction *actionFitLinear;
    QAction *actionFitPolynomial;
    QAction *actionFitExponentialGrowth;
    QAction *actionFitBoltzmannSigmoid;
    QAction *actionFitGaussian;
    QAction *actionFitLorentzian;
    QAction *actionFirstOrderExponentialDecay;
    QAction *actionSecondOrderExponentialDecay;
    QAction *actionThirdOrderExponentialDecay;
    QAction *actionMultiPeakGaussian;
    QAction *actionMultiPeakLorentzian;
    QAction *actionTableFFT;
    QAction *actionTableFitWizard;
    QAction *actionFormatPlot;
    QAction *actionFormatScale;
    QAction *actionFormatAxis;
    QAction *actionFormatGrid;
    QAction *actionFormatTitle;
    QAction *actionDisableGraphTools;
    QAction *actionGraphRescaleShowAll;
    QAction *actionGraphScreenReader;
    QAction *actionGraphDataReader;
    QAction *actionGraphSelectDataRange;
    QAction *actionGraphMoveDataPoints;
    QAction *actionGraphRemoveBadDataPoints;
    QAction *actionPlot2DChannelFill;
    QAction *actionPlot2DVerticalStackedBars;
    QAction *actionPlot2DHorizontalStackedBars;
    QAction *actionGraphDragRange;
    QAction *actionGraphZoomRange;
    QAction *actionPlot2DHalfPie;
    QAction *action3DPolarSpectrogram;
    QAction *action3DWireFramePolar;
    QAction *action3DSurfacePolar;
    QAction *action3DWireFrameSurfacePolar;
    QAction *action3DScatterPolar;
    QAction *actionAddLayoutUp;
    QAction *actionAddLayoutDown;
    QAction *actionAddLayoutLeft;
    QAction *actionAddLayoutRight;
    QAction *actionPlot2DVerticalGroupedBars;
    QAction *actionPlot2DHorizontalGroupedBars;
    QAction *actionPlot2DScatterXErr;
    QAction *actionPlot2DScatterYErr;
    QAction *actionPlot2DScatterXYErr;
    QAction *actionPlot2DScatter;
    QAction *actionAddGlyphs;
    QAction *actionLeftValue;
    QAction *actionLeftLog;
    QAction *actionLeftPi;
    QAction *actionLeftText;
    QAction *actionLeftTime;
    QAction *actionLeftDateTime;
    QAction *actionBottomValue;
    QAction *actionBottomLog;
    QAction *actionBottomPi;
    QAction *actionBottomText;
    QAction *actionBottomTime;
    QAction *actionBottomDateTime;
    QAction *actionRightValue;
    QAction *actionRightLog;
    QAction *actionRightPi;
    QAction *actionRightText;
    QAction *actionRightTime;
    QAction *actionRightDateTime;
    QAction *actionTopValue;
    QAction *actionTopPi;
    QAction *actionTopLog;
    QAction *actionTopText;
    QAction *actionTopTime;
    QAction *actionTopDateTime;
    QAction *actionLegendReorder;
    QAction *actionAddRemovePloty;
    QAction *actionAddRemoveVector;
    QWidget *centralWidget;
    QGridLayout *gridLayout;
    QMdiArea *mdiArea;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menuExportGraph;
    QMenu *menuNew;
    QMenu *menuRecentProjects;
    QMenu *menuEdit;
    QMenu *menuView;
    QMenu *menuToolbars;
    QMenu *menuGraph;
    QMenu *menuAddLayout;
    QMenu *menuAddAxis;
    QMenu *menuAddLeftAxis;
    QMenu *menuAddBottomAxis;
    QMenu *menuAddRightAxis;
    QMenu *menuAddTopAxis;
    QMenu *menuAddRemoveOtherPlots;
    QMenu *menuHelp;
    QMenu *menuPlot;
    QMenu *menuPlot2DSpecialLineSymbol;
    QMenu *menuPlot2DStatisticalGraphs;
    QMenu *menuPlot2DLayoutGrids;
    QMenu *menuPlot3D;
    QMenu *menuPlot2DScatter;
    QMenu *menuScripting;
    QMenu *menu3DPlot;
    QMenu *menuWindow;
    QMenu *menuGraph2DAnalysis;
    QMenu *menuTranslate;
    QMenu *menuSmooth;
    QMenu *menuFFTFilter;
    QMenu *menuQuickFit;
    QMenu *menuFitExponentialDecay;
    QMenu *menuFitMultiPeak;
    QMenu *menuTableAnalysis;
    QMenu *menuTools;
    QMenu *menuTable;
    QMenu *menuMatrix;
    QStatusBar *statusBar;
    QDockWidget *explorerWindow;
    QWidget *dockWidgetContents;
    QGridLayout *explorerGridLayout;
    QSplitter *explorerSplitter;
    FolderTreeWidget *folderView;
    FolderTreeWidget *listView;
    QDockWidget *logWindow;
    QWidget *dockWidgetContents_6;
    QGridLayout *resultLogGridLayout;
    QTextEdit *resultLog;

    void setupUi(QMainWindow *ApplicationWindow)
    {
        if (ApplicationWindow->objectName().isEmpty())
            ApplicationWindow->setObjectName("ApplicationWindow");
        ApplicationWindow->resize(779, 519);
        actionOpenAproj = new QAction(ApplicationWindow);
        actionOpenAproj->setObjectName("actionOpenAproj");
        actionOpenImage = new QAction(ApplicationWindow);
        actionOpenImage->setObjectName("actionOpenImage");
        actionImportImage = new QAction(ApplicationWindow);
        actionImportImage->setObjectName("actionImportImage");
        actionSaveProject = new QAction(ApplicationWindow);
        actionSaveProject->setObjectName("actionSaveProject");
        actionSaveProjectAs = new QAction(ApplicationWindow);
        actionSaveProjectAs->setObjectName("actionSaveProjectAs");
        actionOpenTemplate = new QAction(ApplicationWindow);
        actionOpenTemplate->setObjectName("actionOpenTemplate");
        actionSaveAsTemplate = new QAction(ApplicationWindow);
        actionSaveAsTemplate->setObjectName("actionSaveAsTemplate");
        actionPrint = new QAction(ApplicationWindow);
        actionPrint->setObjectName("actionPrint");
        actionPrintAllPlots = new QAction(ApplicationWindow);
        actionPrintAllPlots->setObjectName("actionPrintAllPlots");
        actionExportASCII = new QAction(ApplicationWindow);
        actionExportASCII->setObjectName("actionExportASCII");
        actionImportASCII = new QAction(ApplicationWindow);
        actionImportASCII->setObjectName("actionImportASCII");
        actionQuit = new QAction(ApplicationWindow);
        actionQuit->setObjectName("actionQuit");
        actionNewProject = new QAction(ApplicationWindow);
        actionNewProject->setObjectName("actionNewProject");
        actionNewTable = new QAction(ApplicationWindow);
        actionNewTable->setObjectName("actionNewTable");
        actionNewTable->setAutoRepeat(true);
        actionNewTable->setVisible(true);
        actionNewTable->setIconVisibleInMenu(true);
        actionNewMatrix = new QAction(ApplicationWindow);
        actionNewMatrix->setObjectName("actionNewMatrix");
        actionNewNote = new QAction(ApplicationWindow);
        actionNewNote->setObjectName("actionNewNote");
        actionNewGraph = new QAction(ApplicationWindow);
        actionNewGraph->setObjectName("actionNewGraph");
        actionNewFunctionPlot = new QAction(ApplicationWindow);
        actionNewFunctionPlot->setObjectName("actionNewFunctionPlot");
        actionNew3DSurfacePlot = new QAction(ApplicationWindow);
        actionNew3DSurfacePlot->setObjectName("actionNew3DSurfacePlot");
        actionExportCurrentGraph = new QAction(ApplicationWindow);
        actionExportCurrentGraph->setObjectName("actionExportCurrentGraph");
        actionExportAllGraphs = new QAction(ApplicationWindow);
        actionExportAllGraphs->setObjectName("actionExportAllGraphs");
        actionUndo = new QAction(ApplicationWindow);
        actionUndo->setObjectName("actionUndo");
        actionRedo = new QAction(ApplicationWindow);
        actionRedo->setObjectName("actionRedo");
        actionCutSelection = new QAction(ApplicationWindow);
        actionCutSelection->setObjectName("actionCutSelection");
        actionCopySelection = new QAction(ApplicationWindow);
        actionCopySelection->setObjectName("actionCopySelection");
        actionClearSelection = new QAction(ApplicationWindow);
        actionClearSelection->setObjectName("actionClearSelection");
        actionPasteSelection = new QAction(ApplicationWindow);
        actionPasteSelection->setObjectName("actionPasteSelection");
        actionDeleteFitTables = new QAction(ApplicationWindow);
        actionDeleteFitTables->setObjectName("actionDeleteFitTables");
        actionClearLogInfo = new QAction(ApplicationWindow);
        actionClearLogInfo->setObjectName("actionClearLogInfo");
        actionPreferences = new QAction(ApplicationWindow);
        actionPreferences->setObjectName("actionPreferences");
        actionShowFileToolbar = new QAction(ApplicationWindow);
        actionShowFileToolbar->setObjectName("actionShowFileToolbar");
        actionShowFileToolbar->setCheckable(true);
        actionShowEditToolbar = new QAction(ApplicationWindow);
        actionShowEditToolbar->setObjectName("actionShowEditToolbar");
        actionShowEditToolbar->setCheckable(true);
        actionShowGraphToolbar = new QAction(ApplicationWindow);
        actionShowGraphToolbar->setObjectName("actionShowGraphToolbar");
        actionShowGraphToolbar->setCheckable(true);
        actionShowPlotToolbar = new QAction(ApplicationWindow);
        actionShowPlotToolbar->setObjectName("actionShowPlotToolbar");
        actionShowPlotToolbar->setCheckable(true);
        actionShowTableToolbar = new QAction(ApplicationWindow);
        actionShowTableToolbar->setObjectName("actionShowTableToolbar");
        actionShowTableToolbar->setCheckable(true);
        actionShowMatrixPlotToolbar = new QAction(ApplicationWindow);
        actionShowMatrixPlotToolbar->setObjectName("actionShowMatrixPlotToolbar");
        actionShowMatrixPlotToolbar->setCheckable(true);
        actionShow3DSurfacePlotToolbar = new QAction(ApplicationWindow);
        actionShow3DSurfacePlotToolbar->setObjectName("actionShow3DSurfacePlotToolbar");
        actionShow3DSurfacePlotToolbar->setCheckable(true);
        actionLockToolbars = new QAction(ApplicationWindow);
        actionLockToolbars->setObjectName("actionLockToolbars");
        actionLockToolbars->setCheckable(true);
        actionPlotWizard = new QAction(ApplicationWindow);
        actionPlotWizard->setObjectName("actionPlotWizard");
        actionShowUndoRedoHistory = new QAction(ApplicationWindow);
        actionShowUndoRedoHistory->setObjectName("actionShowUndoRedoHistory");
        actionAddRemoveCurve = new QAction(ApplicationWindow);
        actionAddRemoveCurve->setObjectName("actionAddRemoveCurve");
        actionAddErrorBars = new QAction(ApplicationWindow);
        actionAddErrorBars->setObjectName("actionAddErrorBars");
        actionAddFunctionCurve = new QAction(ApplicationWindow);
        actionAddFunctionCurve->setObjectName("actionAddFunctionCurve");
        actionAddText = new QAction(ApplicationWindow);
        actionAddText->setObjectName("actionAddText");
        actionDrawArrow = new QAction(ApplicationWindow);
        actionDrawArrow->setObjectName("actionDrawArrow");
        actionDrawArrow->setCheckable(false);
        actionDrawLine = new QAction(ApplicationWindow);
        actionDrawLine->setObjectName("actionDrawLine");
        actionDrawLine->setCheckable(false);
        actionAddTimeStamp = new QAction(ApplicationWindow);
        actionAddTimeStamp->setObjectName("actionAddTimeStamp");
        actionAddImage = new QAction(ApplicationWindow);
        actionAddImage->setObjectName("actionAddImage");
        actionDrawEllipse = new QAction(ApplicationWindow);
        actionDrawEllipse->setObjectName("actionDrawEllipse");
        actionAddNestedLayout = new QAction(ApplicationWindow);
        actionAddNestedLayout->setObjectName("actionAddNestedLayout");
        actionRemoveLayout = new QAction(ApplicationWindow);
        actionRemoveLayout->setObjectName("actionRemoveLayout");
        actionArrangeLayout = new QAction(ApplicationWindow);
        actionArrangeLayout->setObjectName("actionArrangeLayout");
        actionHelp = new QAction(ApplicationWindow);
        actionHelp->setObjectName("actionHelp");
        actionHomepage = new QAction(ApplicationWindow);
        actionHomepage->setObjectName("actionHomepage");
        actionChooseHelpFolder = new QAction(ApplicationWindow);
        actionChooseHelpFolder->setObjectName("actionChooseHelpFolder");
        actionCheckUpdates = new QAction(ApplicationWindow);
        actionCheckUpdates->setObjectName("actionCheckUpdates");
        actionDownloadManual = new QAction(ApplicationWindow);
        actionDownloadManual->setObjectName("actionDownloadManual");
        actionVisitForum = new QAction(ApplicationWindow);
        actionVisitForum->setObjectName("actionVisitForum");
        actionReportBug = new QAction(ApplicationWindow);
        actionReportBug->setObjectName("actionReportBug");
        actionAbout = new QAction(ApplicationWindow);
        actionAbout->setObjectName("actionAbout");
        actionPlot2DLine = new QAction(ApplicationWindow);
        actionPlot2DLine->setObjectName("actionPlot2DLine");
        actionPlot2DVerticalBars = new QAction(ApplicationWindow);
        actionPlot2DVerticalBars->setObjectName("actionPlot2DVerticalBars");
        actionPlot2DHorizontalBars = new QAction(ApplicationWindow);
        actionPlot2DHorizontalBars->setObjectName("actionPlot2DHorizontalBars");
        actionPlot2DArea = new QAction(ApplicationWindow);
        actionPlot2DArea->setObjectName("actionPlot2DArea");
        actionPlot2DPie = new QAction(ApplicationWindow);
        actionPlot2DPie->setObjectName("actionPlot2DPie");
        actionPlot2DVectorsXYXY = new QAction(ApplicationWindow);
        actionPlot2DVectorsXYXY->setObjectName("actionPlot2DVectorsXYXY");
        actionPlot2DVectorsXYAM = new QAction(ApplicationWindow);
        actionPlot2DVectorsXYAM->setObjectName("actionPlot2DVectorsXYAM");
        actionPlot2DVerticalDropLines = new QAction(ApplicationWindow);
        actionPlot2DVerticalDropLines->setObjectName("actionPlot2DVerticalDropLines");
        actionPlot2DSpline = new QAction(ApplicationWindow);
        actionPlot2DSpline->setObjectName("actionPlot2DSpline");
        actionPlot2DVerticalSteps = new QAction(ApplicationWindow);
        actionPlot2DVerticalSteps->setObjectName("actionPlot2DVerticalSteps");
        actionPlot2DHorizontalSteps = new QAction(ApplicationWindow);
        actionPlot2DHorizontalSteps->setObjectName("actionPlot2DHorizontalSteps");
        actionPlot2DStatBox = new QAction(ApplicationWindow);
        actionPlot2DStatBox->setObjectName("actionPlot2DStatBox");
        actionPlot2DStatHistogram = new QAction(ApplicationWindow);
        actionPlot2DStatHistogram->setObjectName("actionPlot2DStatHistogram");
        actionPlot2DStatStackedHistogram = new QAction(ApplicationWindow);
        actionPlot2DStatStackedHistogram->setObjectName("actionPlot2DStatStackedHistogram");
        actionPanelVertical2Layouts = new QAction(ApplicationWindow);
        actionPanelVertical2Layouts->setObjectName("actionPanelVertical2Layouts");
        actionPanelHorizontal2Layouts = new QAction(ApplicationWindow);
        actionPanelHorizontal2Layouts->setObjectName("actionPanelHorizontal2Layouts");
        actionPanel4Layouts = new QAction(ApplicationWindow);
        actionPanel4Layouts->setObjectName("actionPanel4Layouts");
        actionPlot3DRibbon = new QAction(ApplicationWindow);
        actionPlot3DRibbon->setObjectName("actionPlot3DRibbon");
        actionPlot3DBar = new QAction(ApplicationWindow);
        actionPlot3DBar->setObjectName("actionPlot3DBar");
        actionPlot3DScatter = new QAction(ApplicationWindow);
        actionPlot3DScatter->setObjectName("actionPlot3DScatter");
        actionPlot3DTrajectory = new QAction(ApplicationWindow);
        actionPlot3DTrajectory->setObjectName("actionPlot3DTrajectory");
        actionPlot2DLineSymbol = new QAction(ApplicationWindow);
        actionPlot2DLineSymbol->setObjectName("actionPlot2DLineSymbol");
        actionScriptingLanguage = new QAction(ApplicationWindow);
        actionScriptingLanguage->setObjectName("actionScriptingLanguage");
        actionRestartScripting = new QAction(ApplicationWindow);
        actionRestartScripting->setObjectName("actionRestartScripting");
        actionExecute = new QAction(ApplicationWindow);
        actionExecute->setObjectName("actionExecute");
        actionExecuteAll = new QAction(ApplicationWindow);
        actionExecuteAll->setObjectName("actionExecuteAll");
        actionEvaluateExpression = new QAction(ApplicationWindow);
        actionEvaluateExpression->setObjectName("actionEvaluateExpression");
        action3DWireFrame = new QAction(ApplicationWindow);
        action3DWireFrame->setObjectName("action3DWireFrame");
        action3DSurface = new QAction(ApplicationWindow);
        action3DSurface->setObjectName("action3DSurface");
        action3DWireSurface = new QAction(ApplicationWindow);
        action3DWireSurface->setObjectName("action3DWireSurface");
        action3DBar = new QAction(ApplicationWindow);
        action3DBar->setObjectName("action3DBar");
        action3DScatter = new QAction(ApplicationWindow);
        action3DScatter->setObjectName("action3DScatter");
        action3DCountourColorFill = new QAction(ApplicationWindow);
        action3DCountourColorFill->setObjectName("action3DCountourColorFill");
        action3DCountourLines = new QAction(ApplicationWindow);
        action3DCountourLines->setObjectName("action3DCountourLines");
        action3DGreyScaleMap = new QAction(ApplicationWindow);
        action3DGreyScaleMap->setObjectName("action3DGreyScaleMap");
        actionCascadeWindow = new QAction(ApplicationWindow);
        actionCascadeWindow->setObjectName("actionCascadeWindow");
        actionTileWindow = new QAction(ApplicationWindow);
        actionTileWindow->setObjectName("actionTileWindow");
        actionNextWindow = new QAction(ApplicationWindow);
        actionNextWindow->setObjectName("actionNextWindow");
        actionPreviousWindow = new QAction(ApplicationWindow);
        actionPreviousWindow->setObjectName("actionPreviousWindow");
        actionDuplicateWindow = new QAction(ApplicationWindow);
        actionDuplicateWindow->setObjectName("actionDuplicateWindow");
        actionHideWindow = new QAction(ApplicationWindow);
        actionHideWindow->setObjectName("actionHideWindow");
        actionCloseWindow = new QAction(ApplicationWindow);
        actionCloseWindow->setObjectName("actionCloseWindow");
        actionStatisticsOnColumns = new QAction(ApplicationWindow);
        actionStatisticsOnColumns->setObjectName("actionStatisticsOnColumns");
        actionStatisticsOnRows = new QAction(ApplicationWindow);
        actionStatisticsOnRows->setObjectName("actionStatisticsOnRows");
        actionGraph2DFFT = new QAction(ApplicationWindow);
        actionGraph2DFFT->setObjectName("actionGraph2DFFT");
        actionCorrelate = new QAction(ApplicationWindow);
        actionCorrelate->setObjectName("actionCorrelate");
        actionAutocorrelate = new QAction(ApplicationWindow);
        actionAutocorrelate->setObjectName("actionAutocorrelate");
        actionConvolute = new QAction(ApplicationWindow);
        actionConvolute->setObjectName("actionConvolute");
        actionDeconvolute = new QAction(ApplicationWindow);
        actionDeconvolute->setObjectName("actionDeconvolute");
        actionGraph2DFitWizard = new QAction(ApplicationWindow);
        actionGraph2DFitWizard->setObjectName("actionGraph2DFitWizard");
        actionHorizontalTranslate = new QAction(ApplicationWindow);
        actionHorizontalTranslate->setObjectName("actionHorizontalTranslate");
        actionVerticalTranslate = new QAction(ApplicationWindow);
        actionVerticalTranslate->setObjectName("actionVerticalTranslate");
        actionDifferentiate = new QAction(ApplicationWindow);
        actionDifferentiate->setObjectName("actionDifferentiate");
        actionIntegrate = new QAction(ApplicationWindow);
        actionIntegrate->setObjectName("actionIntegrate");
        actionInterpolate = new QAction(ApplicationWindow);
        actionInterpolate->setObjectName("actionInterpolate");
        actionSavitzkySmooth = new QAction(ApplicationWindow);
        actionSavitzkySmooth->setObjectName("actionSavitzkySmooth");
        actionMovingWindowAverageSmooth = new QAction(ApplicationWindow);
        actionMovingWindowAverageSmooth->setObjectName("actionMovingWindowAverageSmooth");
        actionFFTFilterSmooth = new QAction(ApplicationWindow);
        actionFFTFilterSmooth->setObjectName("actionFFTFilterSmooth");
        actionLowPassFFTFilter = new QAction(ApplicationWindow);
        actionLowPassFFTFilter->setObjectName("actionLowPassFFTFilter");
        actionHighPassFFTFilter = new QAction(ApplicationWindow);
        actionHighPassFFTFilter->setObjectName("actionHighPassFFTFilter");
        actionBandPassFFTFilter = new QAction(ApplicationWindow);
        actionBandPassFFTFilter->setObjectName("actionBandPassFFTFilter");
        actionBandBlockFFTFilter = new QAction(ApplicationWindow);
        actionBandBlockFFTFilter->setObjectName("actionBandBlockFFTFilter");
        actionFitLinear = new QAction(ApplicationWindow);
        actionFitLinear->setObjectName("actionFitLinear");
        actionFitPolynomial = new QAction(ApplicationWindow);
        actionFitPolynomial->setObjectName("actionFitPolynomial");
        actionFitExponentialGrowth = new QAction(ApplicationWindow);
        actionFitExponentialGrowth->setObjectName("actionFitExponentialGrowth");
        actionFitBoltzmannSigmoid = new QAction(ApplicationWindow);
        actionFitBoltzmannSigmoid->setObjectName("actionFitBoltzmannSigmoid");
        actionFitGaussian = new QAction(ApplicationWindow);
        actionFitGaussian->setObjectName("actionFitGaussian");
        actionFitLorentzian = new QAction(ApplicationWindow);
        actionFitLorentzian->setObjectName("actionFitLorentzian");
        actionFirstOrderExponentialDecay = new QAction(ApplicationWindow);
        actionFirstOrderExponentialDecay->setObjectName("actionFirstOrderExponentialDecay");
        actionSecondOrderExponentialDecay = new QAction(ApplicationWindow);
        actionSecondOrderExponentialDecay->setObjectName("actionSecondOrderExponentialDecay");
        actionThirdOrderExponentialDecay = new QAction(ApplicationWindow);
        actionThirdOrderExponentialDecay->setObjectName("actionThirdOrderExponentialDecay");
        actionMultiPeakGaussian = new QAction(ApplicationWindow);
        actionMultiPeakGaussian->setObjectName("actionMultiPeakGaussian");
        actionMultiPeakLorentzian = new QAction(ApplicationWindow);
        actionMultiPeakLorentzian->setObjectName("actionMultiPeakLorentzian");
        actionTableFFT = new QAction(ApplicationWindow);
        actionTableFFT->setObjectName("actionTableFFT");
        actionTableFitWizard = new QAction(ApplicationWindow);
        actionTableFitWizard->setObjectName("actionTableFitWizard");
        actionFormatPlot = new QAction(ApplicationWindow);
        actionFormatPlot->setObjectName("actionFormatPlot");
        actionFormatScale = new QAction(ApplicationWindow);
        actionFormatScale->setObjectName("actionFormatScale");
        actionFormatAxis = new QAction(ApplicationWindow);
        actionFormatAxis->setObjectName("actionFormatAxis");
        actionFormatGrid = new QAction(ApplicationWindow);
        actionFormatGrid->setObjectName("actionFormatGrid");
        actionFormatTitle = new QAction(ApplicationWindow);
        actionFormatTitle->setObjectName("actionFormatTitle");
        actionDisableGraphTools = new QAction(ApplicationWindow);
        actionDisableGraphTools->setObjectName("actionDisableGraphTools");
        actionGraphRescaleShowAll = new QAction(ApplicationWindow);
        actionGraphRescaleShowAll->setObjectName("actionGraphRescaleShowAll");
        actionGraphScreenReader = new QAction(ApplicationWindow);
        actionGraphScreenReader->setObjectName("actionGraphScreenReader");
        actionGraphDataReader = new QAction(ApplicationWindow);
        actionGraphDataReader->setObjectName("actionGraphDataReader");
        actionGraphSelectDataRange = new QAction(ApplicationWindow);
        actionGraphSelectDataRange->setObjectName("actionGraphSelectDataRange");
        actionGraphMoveDataPoints = new QAction(ApplicationWindow);
        actionGraphMoveDataPoints->setObjectName("actionGraphMoveDataPoints");
        actionGraphRemoveBadDataPoints = new QAction(ApplicationWindow);
        actionGraphRemoveBadDataPoints->setObjectName("actionGraphRemoveBadDataPoints");
        actionPlot2DChannelFill = new QAction(ApplicationWindow);
        actionPlot2DChannelFill->setObjectName("actionPlot2DChannelFill");
        actionPlot2DVerticalStackedBars = new QAction(ApplicationWindow);
        actionPlot2DVerticalStackedBars->setObjectName("actionPlot2DVerticalStackedBars");
        actionPlot2DHorizontalStackedBars = new QAction(ApplicationWindow);
        actionPlot2DHorizontalStackedBars->setObjectName("actionPlot2DHorizontalStackedBars");
        actionGraphDragRange = new QAction(ApplicationWindow);
        actionGraphDragRange->setObjectName("actionGraphDragRange");
        actionGraphZoomRange = new QAction(ApplicationWindow);
        actionGraphZoomRange->setObjectName("actionGraphZoomRange");
        actionPlot2DHalfPie = new QAction(ApplicationWindow);
        actionPlot2DHalfPie->setObjectName("actionPlot2DHalfPie");
        action3DPolarSpectrogram = new QAction(ApplicationWindow);
        action3DPolarSpectrogram->setObjectName("action3DPolarSpectrogram");
        action3DWireFramePolar = new QAction(ApplicationWindow);
        action3DWireFramePolar->setObjectName("action3DWireFramePolar");
        action3DSurfacePolar = new QAction(ApplicationWindow);
        action3DSurfacePolar->setObjectName("action3DSurfacePolar");
        action3DWireFrameSurfacePolar = new QAction(ApplicationWindow);
        action3DWireFrameSurfacePolar->setObjectName("action3DWireFrameSurfacePolar");
        action3DScatterPolar = new QAction(ApplicationWindow);
        action3DScatterPolar->setObjectName("action3DScatterPolar");
        actionAddLayoutUp = new QAction(ApplicationWindow);
        actionAddLayoutUp->setObjectName("actionAddLayoutUp");
        actionAddLayoutDown = new QAction(ApplicationWindow);
        actionAddLayoutDown->setObjectName("actionAddLayoutDown");
        actionAddLayoutLeft = new QAction(ApplicationWindow);
        actionAddLayoutLeft->setObjectName("actionAddLayoutLeft");
        actionAddLayoutRight = new QAction(ApplicationWindow);
        actionAddLayoutRight->setObjectName("actionAddLayoutRight");
        actionPlot2DVerticalGroupedBars = new QAction(ApplicationWindow);
        actionPlot2DVerticalGroupedBars->setObjectName("actionPlot2DVerticalGroupedBars");
        actionPlot2DHorizontalGroupedBars = new QAction(ApplicationWindow);
        actionPlot2DHorizontalGroupedBars->setObjectName("actionPlot2DHorizontalGroupedBars");
        actionPlot2DScatterXErr = new QAction(ApplicationWindow);
        actionPlot2DScatterXErr->setObjectName("actionPlot2DScatterXErr");
        actionPlot2DScatterYErr = new QAction(ApplicationWindow);
        actionPlot2DScatterYErr->setObjectName("actionPlot2DScatterYErr");
        actionPlot2DScatterXYErr = new QAction(ApplicationWindow);
        actionPlot2DScatterXYErr->setObjectName("actionPlot2DScatterXYErr");
        actionPlot2DScatter = new QAction(ApplicationWindow);
        actionPlot2DScatter->setObjectName("actionPlot2DScatter");
        actionAddGlyphs = new QAction(ApplicationWindow);
        actionAddGlyphs->setObjectName("actionAddGlyphs");
        actionLeftValue = new QAction(ApplicationWindow);
        actionLeftValue->setObjectName("actionLeftValue");
        actionLeftLog = new QAction(ApplicationWindow);
        actionLeftLog->setObjectName("actionLeftLog");
        actionLeftPi = new QAction(ApplicationWindow);
        actionLeftPi->setObjectName("actionLeftPi");
        actionLeftText = new QAction(ApplicationWindow);
        actionLeftText->setObjectName("actionLeftText");
        actionLeftTime = new QAction(ApplicationWindow);
        actionLeftTime->setObjectName("actionLeftTime");
        actionLeftDateTime = new QAction(ApplicationWindow);
        actionLeftDateTime->setObjectName("actionLeftDateTime");
        actionBottomValue = new QAction(ApplicationWindow);
        actionBottomValue->setObjectName("actionBottomValue");
        actionBottomLog = new QAction(ApplicationWindow);
        actionBottomLog->setObjectName("actionBottomLog");
        actionBottomPi = new QAction(ApplicationWindow);
        actionBottomPi->setObjectName("actionBottomPi");
        actionBottomText = new QAction(ApplicationWindow);
        actionBottomText->setObjectName("actionBottomText");
        actionBottomTime = new QAction(ApplicationWindow);
        actionBottomTime->setObjectName("actionBottomTime");
        actionBottomDateTime = new QAction(ApplicationWindow);
        actionBottomDateTime->setObjectName("actionBottomDateTime");
        actionRightValue = new QAction(ApplicationWindow);
        actionRightValue->setObjectName("actionRightValue");
        actionRightLog = new QAction(ApplicationWindow);
        actionRightLog->setObjectName("actionRightLog");
        actionRightPi = new QAction(ApplicationWindow);
        actionRightPi->setObjectName("actionRightPi");
        actionRightText = new QAction(ApplicationWindow);
        actionRightText->setObjectName("actionRightText");
        actionRightTime = new QAction(ApplicationWindow);
        actionRightTime->setObjectName("actionRightTime");
        actionRightDateTime = new QAction(ApplicationWindow);
        actionRightDateTime->setObjectName("actionRightDateTime");
        actionTopValue = new QAction(ApplicationWindow);
        actionTopValue->setObjectName("actionTopValue");
        actionTopPi = new QAction(ApplicationWindow);
        actionTopPi->setObjectName("actionTopPi");
        actionTopLog = new QAction(ApplicationWindow);
        actionTopLog->setObjectName("actionTopLog");
        actionTopText = new QAction(ApplicationWindow);
        actionTopText->setObjectName("actionTopText");
        actionTopTime = new QAction(ApplicationWindow);
        actionTopTime->setObjectName("actionTopTime");
        actionTopDateTime = new QAction(ApplicationWindow);
        actionTopDateTime->setObjectName("actionTopDateTime");
        actionLegendReorder = new QAction(ApplicationWindow);
        actionLegendReorder->setObjectName("actionLegendReorder");
        actionAddRemovePloty = new QAction(ApplicationWindow);
        actionAddRemovePloty->setObjectName("actionAddRemovePloty");
        actionAddRemoveVector = new QAction(ApplicationWindow);
        actionAddRemoveVector->setObjectName("actionAddRemoveVector");
        centralWidget = new QWidget(ApplicationWindow);
        centralWidget->setObjectName("centralWidget");
        gridLayout = new QGridLayout(centralWidget);
        gridLayout->setSpacing(6);
        gridLayout->setContentsMargins(11, 11, 11, 11);
        gridLayout->setObjectName("gridLayout");
        mdiArea = new QMdiArea(centralWidget);
        mdiArea->setObjectName("mdiArea");

        gridLayout->addWidget(mdiArea, 0, 0, 1, 1);

        ApplicationWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(ApplicationWindow);
        menuBar->setObjectName("menuBar");
        menuBar->setGeometry(QRect(0, 0, 779, 23));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName("menuFile");
        menuExportGraph = new QMenu(menuFile);
        menuExportGraph->setObjectName("menuExportGraph");
        menuNew = new QMenu(menuFile);
        menuNew->setObjectName("menuNew");
        menuRecentProjects = new QMenu(menuFile);
        menuRecentProjects->setObjectName("menuRecentProjects");
        menuEdit = new QMenu(menuBar);
        menuEdit->setObjectName("menuEdit");
        menuView = new QMenu(menuBar);
        menuView->setObjectName("menuView");
        menuToolbars = new QMenu(menuView);
        menuToolbars->setObjectName("menuToolbars");
        menuGraph = new QMenu(menuBar);
        menuGraph->setObjectName("menuGraph");
        menuAddLayout = new QMenu(menuGraph);
        menuAddLayout->setObjectName("menuAddLayout");
        menuAddAxis = new QMenu(menuGraph);
        menuAddAxis->setObjectName("menuAddAxis");
        menuAddLeftAxis = new QMenu(menuAddAxis);
        menuAddLeftAxis->setObjectName("menuAddLeftAxis");
        menuAddBottomAxis = new QMenu(menuAddAxis);
        menuAddBottomAxis->setObjectName("menuAddBottomAxis");
        menuAddRightAxis = new QMenu(menuAddAxis);
        menuAddRightAxis->setObjectName("menuAddRightAxis");
        menuAddTopAxis = new QMenu(menuAddAxis);
        menuAddTopAxis->setObjectName("menuAddTopAxis");
        menuAddRemoveOtherPlots = new QMenu(menuGraph);
        menuAddRemoveOtherPlots->setObjectName("menuAddRemoveOtherPlots");
        menuHelp = new QMenu(menuBar);
        menuHelp->setObjectName("menuHelp");
        menuPlot = new QMenu(menuBar);
        menuPlot->setObjectName("menuPlot");
        menuPlot2DSpecialLineSymbol = new QMenu(menuPlot);
        menuPlot2DSpecialLineSymbol->setObjectName("menuPlot2DSpecialLineSymbol");
        menuPlot2DStatisticalGraphs = new QMenu(menuPlot);
        menuPlot2DStatisticalGraphs->setObjectName("menuPlot2DStatisticalGraphs");
        menuPlot2DLayoutGrids = new QMenu(menuPlot);
        menuPlot2DLayoutGrids->setObjectName("menuPlot2DLayoutGrids");
        menuPlot3D = new QMenu(menuPlot);
        menuPlot3D->setObjectName("menuPlot3D");
        menuPlot2DScatter = new QMenu(menuPlot);
        menuPlot2DScatter->setObjectName("menuPlot2DScatter");
        menuScripting = new QMenu(menuBar);
        menuScripting->setObjectName("menuScripting");
        menu3DPlot = new QMenu(menuBar);
        menu3DPlot->setObjectName("menu3DPlot");
        menuWindow = new QMenu(menuBar);
        menuWindow->setObjectName("menuWindow");
        menuGraph2DAnalysis = new QMenu(menuBar);
        menuGraph2DAnalysis->setObjectName("menuGraph2DAnalysis");
        menuTranslate = new QMenu(menuGraph2DAnalysis);
        menuTranslate->setObjectName("menuTranslate");
        menuSmooth = new QMenu(menuGraph2DAnalysis);
        menuSmooth->setObjectName("menuSmooth");
        menuFFTFilter = new QMenu(menuGraph2DAnalysis);
        menuFFTFilter->setObjectName("menuFFTFilter");
        menuQuickFit = new QMenu(menuGraph2DAnalysis);
        menuQuickFit->setObjectName("menuQuickFit");
        menuFitExponentialDecay = new QMenu(menuQuickFit);
        menuFitExponentialDecay->setObjectName("menuFitExponentialDecay");
        menuFitMultiPeak = new QMenu(menuQuickFit);
        menuFitMultiPeak->setObjectName("menuFitMultiPeak");
        menuTableAnalysis = new QMenu(menuBar);
        menuTableAnalysis->setObjectName("menuTableAnalysis");
        menuTools = new QMenu(menuBar);
        menuTools->setObjectName("menuTools");
        menuTable = new QMenu(menuBar);
        menuTable->setObjectName("menuTable");
        menuMatrix = new QMenu(menuBar);
        menuMatrix->setObjectName("menuMatrix");
        ApplicationWindow->setMenuBar(menuBar);
        statusBar = new QStatusBar(ApplicationWindow);
        statusBar->setObjectName("statusBar");
        ApplicationWindow->setStatusBar(statusBar);
        explorerWindow = new QDockWidget(ApplicationWindow);
        explorerWindow->setObjectName("explorerWindow");
        dockWidgetContents = new QWidget();
        dockWidgetContents->setObjectName("dockWidgetContents");
        explorerGridLayout = new QGridLayout(dockWidgetContents);
        explorerGridLayout->setSpacing(6);
        explorerGridLayout->setContentsMargins(11, 11, 11, 11);
        explorerGridLayout->setObjectName("explorerGridLayout");
        explorerSplitter = new QSplitter(dockWidgetContents);
        explorerSplitter->setObjectName("explorerSplitter");
        explorerSplitter->setOrientation(Qt::Horizontal);
        folderView = new FolderTreeWidget(explorerSplitter);
        QTreeWidgetItem *__qtreewidgetitem = new QTreeWidgetItem();
        __qtreewidgetitem->setText(0, QString::fromUtf8("1"));
        folderView->setHeaderItem(__qtreewidgetitem);
        folderView->setObjectName("folderView");
        explorerSplitter->addWidget(folderView);
        listView = new FolderTreeWidget(explorerSplitter);
        QTreeWidgetItem *__qtreewidgetitem1 = new QTreeWidgetItem();
        __qtreewidgetitem1->setText(0, QString::fromUtf8("1"));
        listView->setHeaderItem(__qtreewidgetitem1);
        listView->setObjectName("listView");
        explorerSplitter->addWidget(listView);

        explorerGridLayout->addWidget(explorerSplitter, 0, 0, 1, 1);

        explorerWindow->setWidget(dockWidgetContents);
        ApplicationWindow->addDockWidget(Qt::DockWidgetArea::BottomDockWidgetArea, explorerWindow);
        logWindow = new QDockWidget(ApplicationWindow);
        logWindow->setObjectName("logWindow");
        dockWidgetContents_6 = new QWidget();
        dockWidgetContents_6->setObjectName("dockWidgetContents_6");
        resultLogGridLayout = new QGridLayout(dockWidgetContents_6);
        resultLogGridLayout->setSpacing(6);
        resultLogGridLayout->setContentsMargins(11, 11, 11, 11);
        resultLogGridLayout->setObjectName("resultLogGridLayout");
        resultLog = new QTextEdit(dockWidgetContents_6);
        resultLog->setObjectName("resultLog");

        resultLogGridLayout->addWidget(resultLog, 0, 0, 1, 1);

        logWindow->setWidget(dockWidgetContents_6);
        ApplicationWindow->addDockWidget(Qt::DockWidgetArea::TopDockWidgetArea, logWindow);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuEdit->menuAction());
        menuBar->addAction(menuView->menuAction());
        menuBar->addAction(menuScripting->menuAction());
        menuBar->addAction(menuPlot->menuAction());
        menuBar->addAction(menuTableAnalysis->menuAction());
        menuBar->addAction(menuTable->menuAction());
        menuBar->addAction(menuMatrix->menuAction());
        menuBar->addAction(menu3DPlot->menuAction());
        menuBar->addAction(menuGraph->menuAction());
        menuBar->addAction(menuTools->menuAction());
        menuBar->addAction(menuGraph2DAnalysis->menuAction());
        menuBar->addAction(menuWindow->menuAction());
        menuBar->addAction(menuHelp->menuAction());
        menuFile->addAction(menuNew->menuAction());
        menuFile->addAction(actionOpenAproj);
        menuFile->addAction(menuRecentProjects->menuAction());
        menuFile->addSeparator();
        menuFile->addAction(actionOpenImage);
        menuFile->addAction(actionImportImage);
        menuFile->addSeparator();
        menuFile->addAction(actionSaveProject);
        menuFile->addAction(actionSaveProjectAs);
        menuFile->addSeparator();
        menuFile->addAction(actionOpenTemplate);
        menuFile->addAction(actionSaveAsTemplate);
        menuFile->addSeparator();
        menuFile->addAction(menuExportGraph->menuAction());
        menuFile->addAction(actionPrint);
        menuFile->addAction(actionPrintAllPlots);
        menuFile->addSeparator();
        menuFile->addAction(actionExportASCII);
        menuFile->addAction(actionImportASCII);
        menuFile->addSeparator();
        menuFile->addAction(actionQuit);
        menuExportGraph->addAction(actionExportCurrentGraph);
        menuExportGraph->addAction(actionExportAllGraphs);
        menuNew->addAction(actionNewProject);
        menuNew->addAction(actionNewTable);
        menuNew->addAction(actionNewMatrix);
        menuNew->addAction(actionNewNote);
        menuNew->addAction(actionNewGraph);
        menuNew->addAction(actionNewFunctionPlot);
        menuNew->addAction(actionNew3DSurfacePlot);
        menuEdit->addAction(actionUndo);
        menuEdit->addAction(actionRedo);
        menuEdit->addSeparator();
        menuEdit->addAction(actionCutSelection);
        menuEdit->addAction(actionCopySelection);
        menuEdit->addAction(actionPasteSelection);
        menuEdit->addAction(actionClearSelection);
        menuEdit->addSeparator();
        menuEdit->addAction(actionDeleteFitTables);
        menuEdit->addAction(actionClearLogInfo);
        menuEdit->addSeparator();
        menuEdit->addAction(actionAddGlyphs);
        menuEdit->addAction(actionPreferences);
        menuView->addAction(actionPlotWizard);
        menuView->addSeparator();
        menuView->addAction(actionShowUndoRedoHistory);
        menuView->addAction(menuToolbars->menuAction());
        menuView->addAction(actionLockToolbars);
        menuView->addSeparator();
        menuToolbars->addAction(actionShowFileToolbar);
        menuToolbars->addAction(actionShowEditToolbar);
        menuToolbars->addAction(actionShowTableToolbar);
        menuToolbars->addAction(actionShowPlotToolbar);
        menuToolbars->addAction(actionShowMatrixPlotToolbar);
        menuToolbars->addAction(actionShowGraphToolbar);
        menuToolbars->addAction(actionShow3DSurfacePlotToolbar);
        menuGraph->addAction(actionAddRemoveCurve);
        menuGraph->addAction(actionAddFunctionCurve);
        menuGraph->addAction(actionAddErrorBars);
        menuGraph->addAction(menuAddRemoveOtherPlots->menuAction());
        menuGraph->addAction(menuAddAxis->menuAction());
        menuGraph->addAction(actionLegendReorder);
        menuGraph->addSeparator();
        menuGraph->addAction(actionAddText);
        menuGraph->addAction(actionAddTimeStamp);
        menuGraph->addAction(actionAddImage);
        menuGraph->addAction(actionDrawLine);
        menuGraph->addAction(actionDrawArrow);
        menuGraph->addAction(actionDrawEllipse);
        menuGraph->addSeparator();
        menuGraph->addAction(actionAddNestedLayout);
        menuGraph->addAction(menuAddLayout->menuAction());
        menuGraph->addAction(actionRemoveLayout);
        menuGraph->addAction(actionArrangeLayout);
        menuAddLayout->addAction(actionAddLayoutUp);
        menuAddLayout->addAction(actionAddLayoutDown);
        menuAddLayout->addAction(actionAddLayoutLeft);
        menuAddLayout->addAction(actionAddLayoutRight);
        menuAddAxis->addAction(menuAddLeftAxis->menuAction());
        menuAddAxis->addAction(menuAddBottomAxis->menuAction());
        menuAddAxis->addAction(menuAddRightAxis->menuAction());
        menuAddAxis->addAction(menuAddTopAxis->menuAction());
        menuAddLeftAxis->addAction(actionLeftValue);
        menuAddLeftAxis->addAction(actionLeftLog);
        menuAddLeftAxis->addAction(actionLeftPi);
        menuAddLeftAxis->addAction(actionLeftText);
        menuAddLeftAxis->addAction(actionLeftTime);
        menuAddLeftAxis->addAction(actionLeftDateTime);
        menuAddBottomAxis->addAction(actionBottomValue);
        menuAddBottomAxis->addAction(actionBottomLog);
        menuAddBottomAxis->addAction(actionBottomPi);
        menuAddBottomAxis->addAction(actionBottomText);
        menuAddBottomAxis->addAction(actionBottomTime);
        menuAddBottomAxis->addAction(actionBottomDateTime);
        menuAddRightAxis->addAction(actionRightValue);
        menuAddRightAxis->addAction(actionRightLog);
        menuAddRightAxis->addAction(actionRightPi);
        menuAddRightAxis->addAction(actionRightText);
        menuAddRightAxis->addAction(actionRightTime);
        menuAddRightAxis->addAction(actionRightDateTime);
        menuAddTopAxis->addAction(actionTopValue);
        menuAddTopAxis->addAction(actionTopPi);
        menuAddTopAxis->addAction(actionTopLog);
        menuAddTopAxis->addAction(actionTopText);
        menuAddTopAxis->addAction(actionTopTime);
        menuAddTopAxis->addAction(actionTopDateTime);
        menuAddRemoveOtherPlots->addAction(actionAddRemovePloty);
        menuAddRemoveOtherPlots->addAction(actionAddRemoveVector);
        menuHelp->addAction(actionHelp);
        menuHelp->addAction(actionChooseHelpFolder);
        menuHelp->addSeparator();
        menuHelp->addAction(actionHomepage);
        menuHelp->addAction(actionCheckUpdates);
        menuHelp->addAction(actionDownloadManual);
        menuHelp->addSeparator();
        menuHelp->addAction(actionVisitForum);
        menuHelp->addAction(actionReportBug);
        menuHelp->addSeparator();
        menuHelp->addAction(actionAbout);
        menuPlot->addAction(actionPlot2DLine);
        menuPlot->addAction(menuPlot2DScatter->menuAction());
        menuPlot->addAction(actionPlot2DLineSymbol);
        menuPlot->addAction(menuPlot2DSpecialLineSymbol->menuAction());
        menuPlot->addSeparator();
        menuPlot->addAction(actionPlot2DVerticalBars);
        menuPlot->addAction(actionPlot2DVerticalStackedBars);
        menuPlot->addAction(actionPlot2DVerticalGroupedBars);
        menuPlot->addAction(actionPlot2DHorizontalBars);
        menuPlot->addAction(actionPlot2DHorizontalStackedBars);
        menuPlot->addAction(actionPlot2DHorizontalGroupedBars);
        menuPlot->addAction(actionPlot2DArea);
        menuPlot->addAction(actionPlot2DChannelFill);
        menuPlot->addAction(actionPlot2DPie);
        menuPlot->addAction(actionPlot2DHalfPie);
        menuPlot->addAction(actionPlot2DVectorsXYXY);
        menuPlot->addAction(actionPlot2DVectorsXYAM);
        menuPlot->addSeparator();
        menuPlot->addAction(menuPlot2DStatisticalGraphs->menuAction());
        menuPlot->addSeparator();
        menuPlot->addAction(menuPlot3D->menuAction());
        menuPlot->addSeparator();
        menuPlot->addAction(menuPlot2DLayoutGrids->menuAction());
        menuPlot2DSpecialLineSymbol->addAction(actionPlot2DVerticalDropLines);
        menuPlot2DSpecialLineSymbol->addAction(actionPlot2DSpline);
        menuPlot2DSpecialLineSymbol->addAction(actionPlot2DVerticalSteps);
        menuPlot2DSpecialLineSymbol->addAction(actionPlot2DHorizontalSteps);
        menuPlot2DStatisticalGraphs->addAction(actionPlot2DStatBox);
        menuPlot2DStatisticalGraphs->addAction(actionPlot2DStatHistogram);
        menuPlot2DStatisticalGraphs->addAction(actionPlot2DStatStackedHistogram);
        menuPlot2DLayoutGrids->addAction(actionPanelVertical2Layouts);
        menuPlot2DLayoutGrids->addAction(actionPanelHorizontal2Layouts);
        menuPlot2DLayoutGrids->addAction(actionPanel4Layouts);
        menuPlot3D->addAction(actionPlot3DRibbon);
        menuPlot3D->addAction(actionPlot3DBar);
        menuPlot3D->addAction(actionPlot3DScatter);
        menuPlot3D->addAction(actionPlot3DTrajectory);
        menuPlot2DScatter->addAction(actionPlot2DScatter);
        menuPlot2DScatter->addAction(actionPlot2DScatterXErr);
        menuPlot2DScatter->addAction(actionPlot2DScatterYErr);
        menuPlot2DScatter->addAction(actionPlot2DScatterXYErr);
        menuScripting->addAction(actionScriptingLanguage);
        menuScripting->addAction(actionRestartScripting);
        menuScripting->addSeparator();
        menuScripting->addAction(actionExecute);
        menuScripting->addAction(actionExecuteAll);
        menuScripting->addAction(actionEvaluateExpression);
        menu3DPlot->addAction(action3DWireFrame);
        menu3DPlot->addAction(action3DSurface);
        menu3DPlot->addAction(action3DWireSurface);
        menu3DPlot->addSeparator();
        menu3DPlot->addAction(action3DBar);
        menu3DPlot->addAction(action3DScatter);
        menu3DPlot->addSeparator();
        menu3DPlot->addAction(action3DCountourColorFill);
        menu3DPlot->addAction(action3DCountourLines);
        menu3DPlot->addAction(action3DGreyScaleMap);
        menu3DPlot->addSeparator();
        menu3DPlot->addAction(action3DWireFramePolar);
        menu3DPlot->addAction(action3DSurfacePolar);
        menu3DPlot->addAction(action3DWireFrameSurfacePolar);
        menu3DPlot->addSeparator();
        menu3DPlot->addAction(action3DScatterPolar);
        menu3DPlot->addSeparator();
        menu3DPlot->addAction(action3DPolarSpectrogram);
        menuWindow->addAction(actionCascadeWindow);
        menuWindow->addAction(actionTileWindow);
        menuWindow->addSeparator();
        menuWindow->addAction(actionNextWindow);
        menuWindow->addAction(actionPreviousWindow);
        menuWindow->addSeparator();
        menuWindow->addAction(actionDuplicateWindow);
        menuWindow->addSeparator();
        menuWindow->addAction(actionHideWindow);
        menuWindow->addAction(actionCloseWindow);
        menuGraph2DAnalysis->addAction(menuTranslate->menuAction());
        menuGraph2DAnalysis->addSeparator();
        menuGraph2DAnalysis->addAction(actionGraph2DFFT);
        menuGraph2DAnalysis->addAction(menuFFTFilter->menuAction());
        menuGraph2DAnalysis->addAction(menuSmooth->menuAction());
        menuGraph2DAnalysis->addSeparator();
        menuGraph2DAnalysis->addAction(actionDifferentiate);
        menuGraph2DAnalysis->addAction(actionIntegrate);
        menuGraph2DAnalysis->addSeparator();
        menuGraph2DAnalysis->addAction(actionInterpolate);
        menuGraph2DAnalysis->addSeparator();
        menuGraph2DAnalysis->addAction(menuQuickFit->menuAction());
        menuGraph2DAnalysis->addAction(actionGraph2DFitWizard);
        menuTranslate->addAction(actionHorizontalTranslate);
        menuTranslate->addAction(actionVerticalTranslate);
        menuSmooth->addAction(actionSavitzkySmooth);
        menuSmooth->addAction(actionMovingWindowAverageSmooth);
        menuSmooth->addAction(actionFFTFilterSmooth);
        menuFFTFilter->addAction(actionLowPassFFTFilter);
        menuFFTFilter->addAction(actionHighPassFFTFilter);
        menuFFTFilter->addAction(actionBandPassFFTFilter);
        menuFFTFilter->addAction(actionBandBlockFFTFilter);
        menuQuickFit->addAction(actionFitLinear);
        menuQuickFit->addAction(actionFitPolynomial);
        menuQuickFit->addSeparator();
        menuQuickFit->addAction(menuFitExponentialDecay->menuAction());
        menuQuickFit->addAction(actionFitExponentialGrowth);
        menuQuickFit->addAction(actionFitBoltzmannSigmoid);
        menuQuickFit->addAction(actionFitGaussian);
        menuQuickFit->addAction(actionFitLorentzian);
        menuQuickFit->addAction(menuFitMultiPeak->menuAction());
        menuFitExponentialDecay->addAction(actionFirstOrderExponentialDecay);
        menuFitExponentialDecay->addAction(actionSecondOrderExponentialDecay);
        menuFitExponentialDecay->addAction(actionThirdOrderExponentialDecay);
        menuFitMultiPeak->addAction(actionMultiPeakGaussian);
        menuFitMultiPeak->addAction(actionMultiPeakLorentzian);
        menuTableAnalysis->addAction(actionStatisticsOnColumns);
        menuTableAnalysis->addAction(actionStatisticsOnRows);
        menuTableAnalysis->addSeparator();
        menuTableAnalysis->addAction(actionTableFFT);
        menuTableAnalysis->addSeparator();
        menuTableAnalysis->addAction(actionCorrelate);
        menuTableAnalysis->addAction(actionAutocorrelate);
        menuTableAnalysis->addSeparator();
        menuTableAnalysis->addAction(actionConvolute);
        menuTableAnalysis->addAction(actionDeconvolute);
        menuTableAnalysis->addSeparator();
        menuTools->addAction(actionDisableGraphTools);
        menuTools->addAction(actionGraphDataReader);
        menuTools->addAction(actionGraphScreenReader);
        menuTools->addAction(actionGraphSelectDataRange);
        menuTools->addAction(actionGraphMoveDataPoints);
        menuTools->addAction(actionGraphRemoveBadDataPoints);
        menuTools->addSeparator();
        menuTools->addAction(actionGraphDragRange);
        menuTools->addAction(actionGraphZoomRange);
        menuTools->addSeparator();
        menuTools->addAction(actionGraphRescaleShowAll);

        retranslateUi(ApplicationWindow);

        QMetaObject::connectSlotsByName(ApplicationWindow);
    } // setupUi

    void retranslateUi(QMainWindow *ApplicationWindow)
    {
        ApplicationWindow->setWindowTitle(QCoreApplication::translate("ApplicationWindow", "MainWindow", nullptr));
        actionOpenAproj->setText(QCoreApplication::translate("ApplicationWindow", "&Open...", nullptr));
#if QT_CONFIG(shortcut)
        actionOpenAproj->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+O", nullptr));
#endif // QT_CONFIG(shortcut)
        actionOpenImage->setText(QCoreApplication::translate("ApplicationWindow", "Open Image &File...", nullptr));
#if QT_CONFIG(shortcut)
        actionOpenImage->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+I", nullptr));
#endif // QT_CONFIG(shortcut)
        actionImportImage->setText(QCoreApplication::translate("ApplicationWindow", "&Import Image...", nullptr));
        actionSaveProject->setText(QCoreApplication::translate("ApplicationWindow", "&Save Project", nullptr));
#if QT_CONFIG(shortcut)
        actionSaveProject->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+S", nullptr));
#endif // QT_CONFIG(shortcut)
        actionSaveProjectAs->setText(QCoreApplication::translate("ApplicationWindow", "Sa&ve Project As...", nullptr));
        actionOpenTemplate->setText(QCoreApplication::translate("ApplicationWindow", "Open Template...", nullptr));
        actionSaveAsTemplate->setText(QCoreApplication::translate("ApplicationWindow", "Save As Template...", nullptr));
        actionPrint->setText(QCoreApplication::translate("ApplicationWindow", "&Print...", nullptr));
#if QT_CONFIG(shortcut)
        actionPrint->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+P", nullptr));
#endif // QT_CONFIG(shortcut)
        actionPrintAllPlots->setText(QCoreApplication::translate("ApplicationWindow", "Print A&ll Plots...", nullptr));
        actionExportASCII->setText(QCoreApplication::translate("ApplicationWindow", "E&xport ASCII...", nullptr));
        actionImportASCII->setText(QCoreApplication::translate("ApplicationWindow", "I&mport ASCII...", nullptr));
#if QT_CONFIG(shortcut)
        actionImportASCII->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+K", nullptr));
#endif // QT_CONFIG(shortcut)
        actionQuit->setText(QCoreApplication::translate("ApplicationWindow", "&Quit", nullptr));
#if QT_CONFIG(shortcut)
        actionQuit->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+Q", nullptr));
#endif // QT_CONFIG(shortcut)
        actionNewProject->setText(QCoreApplication::translate("ApplicationWindow", "&New Project", nullptr));
#if QT_CONFIG(tooltip)
        actionNewProject->setToolTip(QCoreApplication::translate("ApplicationWindow", "Open a new project", nullptr));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        actionNewProject->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+N", nullptr));
#endif // QT_CONFIG(shortcut)
        actionNewTable->setText(QCoreApplication::translate("ApplicationWindow", "N&ew Table", nullptr));
#if QT_CONFIG(shortcut)
        actionNewTable->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+T", nullptr));
#endif // QT_CONFIG(shortcut)
        actionNewMatrix->setText(QCoreApplication::translate("ApplicationWindow", "New &Matrix", nullptr));
#if QT_CONFIG(shortcut)
        actionNewMatrix->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+M", nullptr));
#endif // QT_CONFIG(shortcut)
        actionNewNote->setText(QCoreApplication::translate("ApplicationWindow", "New Note/&Script", nullptr));
        actionNewGraph->setText(QCoreApplication::translate("ApplicationWindow", "New &Graph", nullptr));
#if QT_CONFIG(shortcut)
        actionNewGraph->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+G", nullptr));
#endif // QT_CONFIG(shortcut)
        actionNewFunctionPlot->setText(QCoreApplication::translate("ApplicationWindow", "New &Function Plot", nullptr));
#if QT_CONFIG(shortcut)
        actionNewFunctionPlot->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+F", nullptr));
#endif // QT_CONFIG(shortcut)
        actionNew3DSurfacePlot->setText(QCoreApplication::translate("ApplicationWindow", "New &3D Surface Plot", nullptr));
#if QT_CONFIG(shortcut)
        actionNew3DSurfacePlot->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+Alt+Z", nullptr));
#endif // QT_CONFIG(shortcut)
        actionExportCurrentGraph->setText(QCoreApplication::translate("ApplicationWindow", "&Current...", nullptr));
#if QT_CONFIG(shortcut)
        actionExportCurrentGraph->setShortcut(QCoreApplication::translate("ApplicationWindow", "Alt+G", nullptr));
#endif // QT_CONFIG(shortcut)
        actionExportAllGraphs->setText(QCoreApplication::translate("ApplicationWindow", "&All..", nullptr));
#if QT_CONFIG(shortcut)
        actionExportAllGraphs->setShortcut(QCoreApplication::translate("ApplicationWindow", "Alt+X", nullptr));
#endif // QT_CONFIG(shortcut)
        actionUndo->setText(QCoreApplication::translate("ApplicationWindow", "&Undo", nullptr));
#if QT_CONFIG(shortcut)
        actionUndo->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+Z", nullptr));
#endif // QT_CONFIG(shortcut)
        actionRedo->setText(QCoreApplication::translate("ApplicationWindow", "&Redo", nullptr));
#if QT_CONFIG(shortcut)
        actionRedo->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+R", nullptr));
#endif // QT_CONFIG(shortcut)
        actionCutSelection->setText(QCoreApplication::translate("ApplicationWindow", "&Cut Selection", nullptr));
#if QT_CONFIG(shortcut)
        actionCutSelection->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+X", nullptr));
#endif // QT_CONFIG(shortcut)
        actionCopySelection->setText(QCoreApplication::translate("ApplicationWindow", "Copy &Selection", nullptr));
#if QT_CONFIG(shortcut)
        actionCopySelection->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+C", nullptr));
#endif // QT_CONFIG(shortcut)
        actionClearSelection->setText(QCoreApplication::translate("ApplicationWindow", "Cl&ear Selection", nullptr));
#if QT_CONFIG(shortcut)
        actionClearSelection->setShortcut(QCoreApplication::translate("ApplicationWindow", "Backspace", nullptr));
#endif // QT_CONFIG(shortcut)
        actionPasteSelection->setText(QCoreApplication::translate("ApplicationWindow", "&Paste Selection", nullptr));
#if QT_CONFIG(shortcut)
        actionPasteSelection->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+V", nullptr));
#endif // QT_CONFIG(shortcut)
        actionDeleteFitTables->setText(QCoreApplication::translate("ApplicationWindow", "&Delete Fit Tables", nullptr));
        actionClearLogInfo->setText(QCoreApplication::translate("ApplicationWindow", "Clear &Log Information", nullptr));
        actionPreferences->setText(QCoreApplication::translate("ApplicationWindow", "Pre&ferences...", nullptr));
        actionShowFileToolbar->setText(QCoreApplication::translate("ApplicationWindow", "&File", nullptr));
        actionShowEditToolbar->setText(QCoreApplication::translate("ApplicationWindow", "&Edit", nullptr));
        actionShowGraphToolbar->setText(QCoreApplication::translate("ApplicationWindow", "&Plot2D Tools", nullptr));
        actionShowPlotToolbar->setText(QCoreApplication::translate("ApplicationWindow", "&Table Plot", nullptr));
        actionShowTableToolbar->setText(QCoreApplication::translate("ApplicationWindow", "&Table", nullptr));
        actionShowMatrixPlotToolbar->setText(QCoreApplication::translate("ApplicationWindow", "&Matrix Plot", nullptr));
        actionShow3DSurfacePlotToolbar->setText(QCoreApplication::translate("ApplicationWindow", "&Plot3D Tools", nullptr));
        actionLockToolbars->setText(QCoreApplication::translate("ApplicationWindow", "&Lock Toolbars", nullptr));
        actionPlotWizard->setText(QCoreApplication::translate("ApplicationWindow", "Plot &Wizard", nullptr));
#if QT_CONFIG(shortcut)
        actionPlotWizard->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+Alt+W", nullptr));
#endif // QT_CONFIG(shortcut)
        actionShowUndoRedoHistory->setText(QCoreApplication::translate("ApplicationWindow", "&Undo/Redo History", nullptr));
        actionAddRemoveCurve->setText(QCoreApplication::translate("ApplicationWindow", "&Add/Remove Plot xy/xyy...", nullptr));
#if QT_CONFIG(shortcut)
        actionAddRemoveCurve->setShortcut(QCoreApplication::translate("ApplicationWindow", "Alt+C", nullptr));
#endif // QT_CONFIG(shortcut)
        actionAddErrorBars->setText(QCoreApplication::translate("ApplicationWindow", "Add &Error Bars...", nullptr));
#if QT_CONFIG(shortcut)
        actionAddErrorBars->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+B", nullptr));
#endif // QT_CONFIG(shortcut)
        actionAddFunctionCurve->setText(QCoreApplication::translate("ApplicationWindow", "Add &Function...", nullptr));
#if QT_CONFIG(shortcut)
        actionAddFunctionCurve->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+Alt+F", nullptr));
#endif // QT_CONFIG(shortcut)
        actionAddText->setText(QCoreApplication::translate("ApplicationWindow", "Add Te&xt", nullptr));
#if QT_CONFIG(shortcut)
        actionAddText->setShortcut(QCoreApplication::translate("ApplicationWindow", "Alt+T", nullptr));
#endif // QT_CONFIG(shortcut)
        actionDrawArrow->setText(QCoreApplication::translate("ApplicationWindow", "&Draw Arrow", nullptr));
#if QT_CONFIG(shortcut)
        actionDrawArrow->setShortcut(QCoreApplication::translate("ApplicationWindow", "Alt+A", nullptr));
#endif // QT_CONFIG(shortcut)
        actionDrawLine->setText(QCoreApplication::translate("ApplicationWindow", "Dra&w Line", nullptr));
        actionAddTimeStamp->setText(QCoreApplication::translate("ApplicationWindow", "Add Ti&me Stamp", nullptr));
#if QT_CONFIG(shortcut)
        actionAddTimeStamp->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+Alt+T", nullptr));
#endif // QT_CONFIG(shortcut)
        actionAddImage->setText(QCoreApplication::translate("ApplicationWindow", "Add &Image", nullptr));
#if QT_CONFIG(shortcut)
        actionAddImage->setShortcut(QCoreApplication::translate("ApplicationWindow", "Alt+I", nullptr));
#endif // QT_CONFIG(shortcut)
        actionDrawEllipse->setText(QCoreApplication::translate("ApplicationWindow", "&Draw Ellipse", nullptr));
        actionDrawEllipse->setIconText(QCoreApplication::translate("ApplicationWindow", "Draw Ellipse", nullptr));
#if QT_CONFIG(tooltip)
        actionDrawEllipse->setToolTip(QCoreApplication::translate("ApplicationWindow", "Draw Ellipse", nullptr));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        actionDrawEllipse->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+L", nullptr));
#endif // QT_CONFIG(shortcut)
        actionAddNestedLayout->setText(QCoreApplication::translate("ApplicationWindow", "Add Nested Layout", nullptr));
        actionRemoveLayout->setText(QCoreApplication::translate("ApplicationWindow", "&Remove Layout", nullptr));
        actionArrangeLayout->setText(QCoreApplication::translate("ApplicationWindow", "Swap Layouts...", nullptr));
        actionHelp->setText(QCoreApplication::translate("ApplicationWindow", "&Help", nullptr));
#if QT_CONFIG(shortcut)
        actionHelp->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+H", nullptr));
#endif // QT_CONFIG(shortcut)
        actionHomepage->setText(QCoreApplication::translate("ApplicationWindow", "&AlphaPlot Homepage", nullptr));
        actionChooseHelpFolder->setText(QCoreApplication::translate("ApplicationWindow", "&Choose Help Folder", nullptr));
        actionCheckUpdates->setText(QCoreApplication::translate("ApplicationWindow", "Check &Updates", nullptr));
        actionDownloadManual->setText(QCoreApplication::translate("ApplicationWindow", "&Download Manual", nullptr));
        actionVisitForum->setText(QCoreApplication::translate("ApplicationWindow", "&Visit AlphaPlot Forum", nullptr));
        actionReportBug->setText(QCoreApplication::translate("ApplicationWindow", "&Report a Bug", nullptr));
        actionAbout->setText(QCoreApplication::translate("ApplicationWindow", "A&bout", nullptr));
#if QT_CONFIG(shortcut)
        actionAbout->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+Alt+H", nullptr));
#endif // QT_CONFIG(shortcut)
        actionPlot2DLine->setText(QCoreApplication::translate("ApplicationWindow", "&Line", nullptr));
        actionPlot2DVerticalBars->setText(QCoreApplication::translate("ApplicationWindow", "&Vertical Bars", nullptr));
        actionPlot2DHorizontalBars->setText(QCoreApplication::translate("ApplicationWindow", "&Horizontal Bars", nullptr));
        actionPlot2DArea->setText(QCoreApplication::translate("ApplicationWindow", "&Area", nullptr));
        actionPlot2DPie->setText(QCoreApplication::translate("ApplicationWindow", "&Pie", nullptr));
        actionPlot2DVectorsXYXY->setText(QCoreApplication::translate("ApplicationWindow", "Vectors &XYXY", nullptr));
        actionPlot2DVectorsXYAM->setText(QCoreApplication::translate("ApplicationWindow", "V&ectors XYAM", nullptr));
        actionPlot2DVerticalDropLines->setText(QCoreApplication::translate("ApplicationWindow", "&Vertical Drop Lines", nullptr));
        actionPlot2DSpline->setText(QCoreApplication::translate("ApplicationWindow", "&Spline", nullptr));
        actionPlot2DVerticalSteps->setText(QCoreApplication::translate("ApplicationWindow", "V&ertical Steps", nullptr));
        actionPlot2DHorizontalSteps->setText(QCoreApplication::translate("ApplicationWindow", "&Horizontal Steps", nullptr));
        actionPlot2DStatBox->setText(QCoreApplication::translate("ApplicationWindow", "&Box Plot", nullptr));
        actionPlot2DStatHistogram->setText(QCoreApplication::translate("ApplicationWindow", "&Histogram", nullptr));
        actionPlot2DStatStackedHistogram->setText(QCoreApplication::translate("ApplicationWindow", "&Stacked Histogram", nullptr));
        actionPanelVertical2Layouts->setText(QCoreApplication::translate("ApplicationWindow", "&Vertical 2 Layouts", nullptr));
        actionPanelHorizontal2Layouts->setText(QCoreApplication::translate("ApplicationWindow", "&Horizontal 2 Layouts", nullptr));
        actionPanel4Layouts->setText(QCoreApplication::translate("ApplicationWindow", "&4(2x2) Layouts", nullptr));
        actionPlot3DRibbon->setText(QCoreApplication::translate("ApplicationWindow", "&Ribbon", nullptr));
        actionPlot3DBar->setText(QCoreApplication::translate("ApplicationWindow", "&Bar", nullptr));
        actionPlot3DScatter->setText(QCoreApplication::translate("ApplicationWindow", "&Scatter", nullptr));
        actionPlot3DTrajectory->setText(QCoreApplication::translate("ApplicationWindow", "&Trajectory", nullptr));
        actionPlot2DLineSymbol->setText(QCoreApplication::translate("ApplicationWindow", "L&ine + Symbol", nullptr));
        actionScriptingLanguage->setText(QCoreApplication::translate("ApplicationWindow", "&Scripting Language", nullptr));
        actionRestartScripting->setText(QCoreApplication::translate("ApplicationWindow", "&Restart Scripting", nullptr));
        actionExecute->setText(QCoreApplication::translate("ApplicationWindow", "&Execute", nullptr));
        actionExecuteAll->setText(QCoreApplication::translate("ApplicationWindow", "E&xecute All", nullptr));
        actionEvaluateExpression->setText(QCoreApplication::translate("ApplicationWindow", "E&valuate Expression", nullptr));
        action3DWireFrame->setText(QCoreApplication::translate("ApplicationWindow", "&3D Wire Frame", nullptr));
        action3DSurface->setText(QCoreApplication::translate("ApplicationWindow", "3D &Surface", nullptr));
        action3DWireSurface->setText(QCoreApplication::translate("ApplicationWindow", "3D &Wire Frame Surface", nullptr));
        action3DBar->setText(QCoreApplication::translate("ApplicationWindow", "&Bar", nullptr));
        action3DScatter->setText(QCoreApplication::translate("ApplicationWindow", "&Scatter", nullptr));
        action3DCountourColorFill->setText(QCoreApplication::translate("ApplicationWindow", "&Countour + Color Fill", nullptr));
        action3DCountourLines->setText(QCoreApplication::translate("ApplicationWindow", "Countour &Lines", nullptr));
        action3DGreyScaleMap->setText(QCoreApplication::translate("ApplicationWindow", "&Grey Scale Map", nullptr));
        actionCascadeWindow->setText(QCoreApplication::translate("ApplicationWindow", "&Cascade", nullptr));
        actionTileWindow->setText(QCoreApplication::translate("ApplicationWindow", "&Tile", nullptr));
        actionNextWindow->setText(QCoreApplication::translate("ApplicationWindow", "&Next", nullptr));
        actionPreviousWindow->setText(QCoreApplication::translate("ApplicationWindow", "&Previous", nullptr));
        actionDuplicateWindow->setText(QCoreApplication::translate("ApplicationWindow", "&Duplicate", nullptr));
        actionHideWindow->setText(QCoreApplication::translate("ApplicationWindow", "&Hide Window", nullptr));
        actionCloseWindow->setText(QCoreApplication::translate("ApplicationWindow", "C&lose Window", nullptr));
#if QT_CONFIG(shortcut)
        actionCloseWindow->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+W", nullptr));
#endif // QT_CONFIG(shortcut)
        actionStatisticsOnColumns->setText(QCoreApplication::translate("ApplicationWindow", "Statistics on Columns", nullptr));
        actionStatisticsOnRows->setText(QCoreApplication::translate("ApplicationWindow", "Statistics on Rows", nullptr));
        actionGraph2DFFT->setText(QCoreApplication::translate("ApplicationWindow", "FFT...", nullptr));
        actionCorrelate->setText(QCoreApplication::translate("ApplicationWindow", "Correlate", nullptr));
        actionAutocorrelate->setText(QCoreApplication::translate("ApplicationWindow", "Autocorrelate", nullptr));
        actionConvolute->setText(QCoreApplication::translate("ApplicationWindow", "Convolute", nullptr));
        actionDeconvolute->setText(QCoreApplication::translate("ApplicationWindow", "Deconvolute", nullptr));
        actionGraph2DFitWizard->setText(QCoreApplication::translate("ApplicationWindow", "Fit Wizard...", nullptr));
#if QT_CONFIG(shortcut)
        actionGraph2DFitWizard->setShortcut(QCoreApplication::translate("ApplicationWindow", "Ctrl+Y", nullptr));
#endif // QT_CONFIG(shortcut)
        actionHorizontalTranslate->setText(QCoreApplication::translate("ApplicationWindow", "Horizontal", nullptr));
        actionVerticalTranslate->setText(QCoreApplication::translate("ApplicationWindow", "Vertical", nullptr));
        actionDifferentiate->setText(QCoreApplication::translate("ApplicationWindow", "Differentiate", nullptr));
        actionIntegrate->setText(QCoreApplication::translate("ApplicationWindow", "Integrate", nullptr));
        actionInterpolate->setText(QCoreApplication::translate("ApplicationWindow", "Interpolate", nullptr));
        actionSavitzkySmooth->setText(QCoreApplication::translate("ApplicationWindow", "Savitzky-Golay...", nullptr));
        actionMovingWindowAverageSmooth->setText(QCoreApplication::translate("ApplicationWindow", "Moving Window Average...", nullptr));
        actionFFTFilterSmooth->setText(QCoreApplication::translate("ApplicationWindow", "FFT Filter...", nullptr));
        actionLowPassFFTFilter->setText(QCoreApplication::translate("ApplicationWindow", "Low Pass...", nullptr));
        actionHighPassFFTFilter->setText(QCoreApplication::translate("ApplicationWindow", "High Pass...", nullptr));
        actionBandPassFFTFilter->setText(QCoreApplication::translate("ApplicationWindow", "Band Pass...", nullptr));
        actionBandBlockFFTFilter->setText(QCoreApplication::translate("ApplicationWindow", "Band Block...", nullptr));
        actionFitLinear->setText(QCoreApplication::translate("ApplicationWindow", "Fit Linear...", nullptr));
        actionFitPolynomial->setText(QCoreApplication::translate("ApplicationWindow", "Fit Polynomial...", nullptr));
        actionFitExponentialGrowth->setText(QCoreApplication::translate("ApplicationWindow", "Fit Exponential Growth...", nullptr));
        actionFitBoltzmannSigmoid->setText(QCoreApplication::translate("ApplicationWindow", "Fit Boltzmann (Sigmoidal)...", nullptr));
        actionFitGaussian->setText(QCoreApplication::translate("ApplicationWindow", "Fit Gaussian...", nullptr));
        actionFitLorentzian->setText(QCoreApplication::translate("ApplicationWindow", "Fit Lorentzian...", nullptr));
        actionFirstOrderExponentialDecay->setText(QCoreApplication::translate("ApplicationWindow", "First Order...", nullptr));
        actionSecondOrderExponentialDecay->setText(QCoreApplication::translate("ApplicationWindow", "Second Order...", nullptr));
        actionThirdOrderExponentialDecay->setText(QCoreApplication::translate("ApplicationWindow", "Third Order...", nullptr));
        actionMultiPeakGaussian->setText(QCoreApplication::translate("ApplicationWindow", "Gaussian...", nullptr));
        actionMultiPeakLorentzian->setText(QCoreApplication::translate("ApplicationWindow", "Lorentzian...", nullptr));
        actionTableFFT->setText(QCoreApplication::translate("ApplicationWindow", "FFT...", nullptr));
        actionTableFitWizard->setText(QCoreApplication::translate("ApplicationWindow", "Fit Wizard...", nullptr));
        actionFormatPlot->setText(QCoreApplication::translate("ApplicationWindow", "Plot...", nullptr));
        actionFormatScale->setText(QCoreApplication::translate("ApplicationWindow", "Scale...", nullptr));
        actionFormatAxis->setText(QCoreApplication::translate("ApplicationWindow", "Axis...", nullptr));
        actionFormatGrid->setText(QCoreApplication::translate("ApplicationWindow", "Grid...", nullptr));
        actionFormatTitle->setText(QCoreApplication::translate("ApplicationWindow", "Title...", nullptr));
        actionDisableGraphTools->setText(QCoreApplication::translate("ApplicationWindow", "Disable Tools", nullptr));
        actionGraphRescaleShowAll->setText(QCoreApplication::translate("ApplicationWindow", "Rescale to Show All", nullptr));
        actionGraphScreenReader->setText(QCoreApplication::translate("ApplicationWindow", "Screen Reader", nullptr));
        actionGraphDataReader->setText(QCoreApplication::translate("ApplicationWindow", "Data Reader", nullptr));
        actionGraphSelectDataRange->setText(QCoreApplication::translate("ApplicationWindow", "Select Data Range", nullptr));
        actionGraphMoveDataPoints->setText(QCoreApplication::translate("ApplicationWindow", "Move Data Points...", nullptr));
        actionGraphRemoveBadDataPoints->setText(QCoreApplication::translate("ApplicationWindow", "Remove Bad Data Points...", nullptr));
        actionPlot2DChannelFill->setText(QCoreApplication::translate("ApplicationWindow", "&Channel Fill", nullptr));
        actionPlot2DVerticalStackedBars->setText(QCoreApplication::translate("ApplicationWindow", "Vertical Stacked Bars", nullptr));
        actionPlot2DHorizontalStackedBars->setText(QCoreApplication::translate("ApplicationWindow", "Horizontal Stacked Bars", nullptr));
        actionGraphDragRange->setText(QCoreApplication::translate("ApplicationWindow", "Drag Range", nullptr));
        actionGraphZoomRange->setText(QCoreApplication::translate("ApplicationWindow", "Zoom Range", nullptr));
        actionPlot2DHalfPie->setText(QCoreApplication::translate("ApplicationWindow", "&Half Pie", nullptr));
        action3DPolarSpectrogram->setText(QCoreApplication::translate("ApplicationWindow", "Polar Spectrogram", nullptr));
        action3DWireFramePolar->setText(QCoreApplication::translate("ApplicationWindow", "3D Wire Frame Polar", nullptr));
        action3DSurfacePolar->setText(QCoreApplication::translate("ApplicationWindow", "3D Surface Polar", nullptr));
        action3DWireFrameSurfacePolar->setText(QCoreApplication::translate("ApplicationWindow", "3D Wire Frame Surface Polar", nullptr));
        action3DScatterPolar->setText(QCoreApplication::translate("ApplicationWindow", "3D Scatter Polar", nullptr));
        actionAddLayoutUp->setText(QCoreApplication::translate("ApplicationWindow", "Add Up", nullptr));
        actionAddLayoutDown->setText(QCoreApplication::translate("ApplicationWindow", "Add Down", nullptr));
        actionAddLayoutLeft->setText(QCoreApplication::translate("ApplicationWindow", "Add Left", nullptr));
        actionAddLayoutRight->setText(QCoreApplication::translate("ApplicationWindow", "Add Right", nullptr));
        actionPlot2DVerticalGroupedBars->setText(QCoreApplication::translate("ApplicationWindow", "Vertical Grouped Bars", nullptr));
        actionPlot2DHorizontalGroupedBars->setText(QCoreApplication::translate("ApplicationWindow", "Horizontal Grouped Bars", nullptr));
        actionPlot2DScatterXErr->setText(QCoreApplication::translate("ApplicationWindow", "Scatter With X Err", nullptr));
        actionPlot2DScatterYErr->setText(QCoreApplication::translate("ApplicationWindow", "Scatter With Y Err", nullptr));
        actionPlot2DScatterXYErr->setText(QCoreApplication::translate("ApplicationWindow", "Scatter With XY Err", nullptr));
        actionPlot2DScatter->setText(QCoreApplication::translate("ApplicationWindow", "Scatter", nullptr));
        actionAddGlyphs->setText(QCoreApplication::translate("ApplicationWindow", "Add Symbols/Glyphs", nullptr));
        actionLeftValue->setText(QCoreApplication::translate("ApplicationWindow", "Value", nullptr));
        actionLeftLog->setText(QCoreApplication::translate("ApplicationWindow", "Log", nullptr));
        actionLeftPi->setText(QCoreApplication::translate("ApplicationWindow", "Pi", nullptr));
        actionLeftText->setText(QCoreApplication::translate("ApplicationWindow", "Text", nullptr));
        actionLeftTime->setText(QCoreApplication::translate("ApplicationWindow", "Time", nullptr));
        actionLeftDateTime->setText(QCoreApplication::translate("ApplicationWindow", "DateTime", nullptr));
        actionBottomValue->setText(QCoreApplication::translate("ApplicationWindow", "Value", nullptr));
        actionBottomLog->setText(QCoreApplication::translate("ApplicationWindow", "Log", nullptr));
        actionBottomPi->setText(QCoreApplication::translate("ApplicationWindow", "Pi", nullptr));
        actionBottomText->setText(QCoreApplication::translate("ApplicationWindow", "Text", nullptr));
        actionBottomTime->setText(QCoreApplication::translate("ApplicationWindow", "Time", nullptr));
        actionBottomDateTime->setText(QCoreApplication::translate("ApplicationWindow", "DateTime", nullptr));
        actionRightValue->setText(QCoreApplication::translate("ApplicationWindow", "Value", nullptr));
        actionRightLog->setText(QCoreApplication::translate("ApplicationWindow", "Log", nullptr));
        actionRightPi->setText(QCoreApplication::translate("ApplicationWindow", "Pi", nullptr));
        actionRightText->setText(QCoreApplication::translate("ApplicationWindow", "Text", nullptr));
        actionRightTime->setText(QCoreApplication::translate("ApplicationWindow", "Time", nullptr));
        actionRightDateTime->setText(QCoreApplication::translate("ApplicationWindow", "DateTime", nullptr));
        actionTopValue->setText(QCoreApplication::translate("ApplicationWindow", "Value", nullptr));
        actionTopPi->setText(QCoreApplication::translate("ApplicationWindow", "Pi", nullptr));
        actionTopLog->setText(QCoreApplication::translate("ApplicationWindow", "Log", nullptr));
        actionTopText->setText(QCoreApplication::translate("ApplicationWindow", "Text", nullptr));
        actionTopTime->setText(QCoreApplication::translate("ApplicationWindow", "Time", nullptr));
        actionTopDateTime->setText(QCoreApplication::translate("ApplicationWindow", "DateTime", nullptr));
        actionLegendReorder->setText(QCoreApplication::translate("ApplicationWindow", "Legend Reorder", nullptr));
        actionAddRemovePloty->setText(QCoreApplication::translate("ApplicationWindow", "Add/Remove Plot y...", nullptr));
        actionAddRemoveVector->setText(QCoreApplication::translate("ApplicationWindow", "Add/Remove Vector Plot...", nullptr));
        menuFile->setTitle(QCoreApplication::translate("ApplicationWindow", "Fi&le", nullptr));
        menuExportGraph->setTitle(QCoreApplication::translate("ApplicationWindow", "&Export Graph", nullptr));
        menuNew->setTitle(QCoreApplication::translate("ApplicationWindow", "&New", nullptr));
        menuRecentProjects->setTitle(QCoreApplication::translate("ApplicationWindow", "&Recent Projects", nullptr));
        menuEdit->setTitle(QCoreApplication::translate("ApplicationWindow", "Edit", nullptr));
        menuView->setTitle(QCoreApplication::translate("ApplicationWindow", "&View", nullptr));
        menuToolbars->setTitle(QCoreApplication::translate("ApplicationWindow", "&Toolbars", nullptr));
        menuGraph->setTitle(QCoreApplication::translate("ApplicationWindow", "&Graph", nullptr));
        menuAddLayout->setTitle(QCoreApplication::translate("ApplicationWindow", "Add &Layout", nullptr));
        menuAddAxis->setTitle(QCoreApplication::translate("ApplicationWindow", "Add Axis...", nullptr));
        menuAddLeftAxis->setTitle(QCoreApplication::translate("ApplicationWindow", "Add Left Axis", nullptr));
        menuAddBottomAxis->setTitle(QCoreApplication::translate("ApplicationWindow", "Add Bottom Axis", nullptr));
        menuAddRightAxis->setTitle(QCoreApplication::translate("ApplicationWindow", "Add Right Axis", nullptr));
        menuAddTopAxis->setTitle(QCoreApplication::translate("ApplicationWindow", "Add Top Axis", nullptr));
        menuAddRemoveOtherPlots->setTitle(QCoreApplication::translate("ApplicationWindow", "Add/Remove Other Plots...", nullptr));
        menuHelp->setTitle(QCoreApplication::translate("ApplicationWindow", "Help", nullptr));
        menuPlot->setTitle(QCoreApplication::translate("ApplicationWindow", "Pl&ot", nullptr));
        menuPlot2DSpecialLineSymbol->setTitle(QCoreApplication::translate("ApplicationWindow", "Spe&cial Line + Symbol", nullptr));
        menuPlot2DStatisticalGraphs->setTitle(QCoreApplication::translate("ApplicationWindow", "Statistical &Graphs", nullptr));
        menuPlot2DLayoutGrids->setTitle(QCoreApplication::translate("ApplicationWindow", "Layout Grids", nullptr));
        menuPlot3D->setTitle(QCoreApplication::translate("ApplicationWindow", "&3D Plot", nullptr));
        menuPlot2DScatter->setTitle(QCoreApplication::translate("ApplicationWindow", "Scatter", nullptr));
        menuScripting->setTitle(QCoreApplication::translate("ApplicationWindow", "Scripti&ng", nullptr));
        menu3DPlot->setTitle(QCoreApplication::translate("ApplicationWindow", "&3D Plot", nullptr));
        menuWindow->setTitle(QCoreApplication::translate("ApplicationWindow", "Windows", nullptr));
        menuGraph2DAnalysis->setTitle(QCoreApplication::translate("ApplicationWindow", "Analysis", nullptr));
        menuTranslate->setTitle(QCoreApplication::translate("ApplicationWindow", "Translate...", nullptr));
        menuSmooth->setTitle(QCoreApplication::translate("ApplicationWindow", "Smooth", nullptr));
        menuFFTFilter->setTitle(QCoreApplication::translate("ApplicationWindow", "FFT Filter", nullptr));
        menuQuickFit->setTitle(QCoreApplication::translate("ApplicationWindow", "Quick Fit", nullptr));
        menuFitExponentialDecay->setTitle(QCoreApplication::translate("ApplicationWindow", "Fit Exponential Decay...", nullptr));
        menuFitMultiPeak->setTitle(QCoreApplication::translate("ApplicationWindow", "Fit Multi-Peak...", nullptr));
        menuTableAnalysis->setTitle(QCoreApplication::translate("ApplicationWindow", "Analysis", nullptr));
        menuTools->setTitle(QCoreApplication::translate("ApplicationWindow", "Tools", nullptr));
        menuTable->setTitle(QCoreApplication::translate("ApplicationWindow", "Table", nullptr));
        menuMatrix->setTitle(QCoreApplication::translate("ApplicationWindow", "Matrix", nullptr));
#if QT_CONFIG(accessibility)
        explorerWindow->setAccessibleName(QCoreApplication::translate("ApplicationWindow", "Project Explorer", nullptr));
#endif // QT_CONFIG(accessibility)
        explorerWindow->setWindowTitle(QCoreApplication::translate("ApplicationWindow", "Project Explorer", nullptr));
        logWindow->setWindowTitle(QCoreApplication::translate("ApplicationWindow", "Results Log", nullptr));
    } // retranslateUi

};

namespace Ui {
    class ApplicationWindow: public Ui_ApplicationWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_APPLICATIONWINDOW_H
